services:
  serialization-libs-demo:
    container_name: serialization-libs-demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME:-serialization-libs-demo}
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-serialization-libs-demo}
    stdin_open: true
    tty: true
    restart: no
